-- MySQL Script generated by MySQL Workbench
-- Tue Jul 14 22:26:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pomodora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pomodora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pomodora` DEFAULT CHARACTER SET utf8 ;
USE `pomodora` ;

-- -----------------------------------------------------
-- Table `pomodora`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomodora`.`users` (
  `user_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(128) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `username` (`username` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `pomodora`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomodora`.`categories` (
  `category_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NULL,
  `category_name` VARCHAR(45) NULL,
  `time_spent` INT NULL,
  `tasks_completed` INT NULL,
  `rank` INT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `pomodora`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomodora`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomodora`.`tasks` (
  `task_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  `task_name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `completed` TINYINT NULL,
  `time_duration` INT NULL,
  `time_completed` INT NULL,
  PRIMARY KEY (`task_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `pomodora`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `pomodora`.`categories` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pomodora`.`reward_ranks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomodora`.`reward_ranks` (
  `rank_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rank_name` VARCHAR(45) NULL,
  `time_required` INT NULL,
  PRIMARY KEY (`rank_id`))
ENGINE = InnoDB;

USE `pomodora` ;

-- -----------------------------------------------------
-- Placeholder table for view `pomodora`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pomodora`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `pomodora`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pomodora`.`view1`;
USE `pomodora`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
